#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)
host = data.get("host")
admin = data.get("admin")
password = data.get("password")
# Upper case to set environment variable and minor case to read from stdin
config = {
    "MINT_URL": host,
    "MINT_USER": admin,
    "MINT_PASS": password,
    "REBUILD_FRONTEND": "no",
    "INSTALL_DEMO_DATA": "no",
    "SSL": "no",
}

agent.write_envfile("minthcm.env", config)

elastic_app = {
    "node_name": "es1",
    "cluster.name": "minthcm",
    "discovery.type": "single-node",
    "xpack.security.enabled": "false",
    "ES_JAVA_OPTS": "-Xms512m -Xmx512m",
}
agent.write_envfile("elastic.env", elastic_app)


# Make sure everything is saved inside the environment file
# just before starting systemd unit
# agent.dump_env()
